league_oauth2_server:
    authorization_server:
        private_key: '%env(resolve:OAUTH_PRIVATE_KEY)%'
        private_key_passphrase: '%env(resolve:OAUTH_PASSPHRASE)%'
        encryption_key: '%env(resolve:OAUTH_ENCRYPTION_KEY)%'
        enable_client_credentials_grant: true
        enable_password_grant: false
        enable_refresh_token_grant: false
        enable_auth_code_grant: false
    resource_server:
        public_key: '%env(resolve:OAUTH_PUBLIC_KEY)%'
    scopes: 
        available: ['api']
        default: ['api']
    persistence:
        doctrine: null

when@test:
    league_oauth2_server:
        persistence:
            in_memory: null
