security:
    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
    providers:
        admin_user_provider:
            id: App\Security\AdminUserProvider
        # api_client_provider:
        #     id: App\Security\ApiClientProvider
        api_client_provider:
            entity:
                class: App\Entity\ApiClient
                property: oauth2ClientIdentifier
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        backend:
            pattern: ^/admin
            lazy: true
            custom_authenticators:
                - App\Security\LoginFormAuthenticator
            provider: admin_user_provider
            logout:
                path: admin_logout
                target: admin_dashboard
        api:
            pattern: ^/api
            security: "%api.use_oauth%"
            stateless: false # To allow bypassing via the session
            provider: api_client_provider
            oauth2: true
  
    # Note: Only the *first* access control that matches will be used
    access_control:
        - { path: ^/admin/login, roles: PUBLIC_ACCESS }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/api/v2/auth/token, roles: PUBLIC_ACCESS }
        - { path: ^/api/v2/$, roles: PUBLIC_ACCESS }
        - { path: ^/api/v2/, roles: [ROLE_OAUTH2_API, ROLE_BYPASS_AUTH_API] }

when@test:
    security:
        password_hashers:
            # By default, password hashers are resource intensive and take time. This is
            # important to generate secure password hashes. In tests however, secure hashes
            # are not important, waste resources and increase test times. The following
            # reduces the work factor to the lowest possible values.
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon

