FROM debian:jessie
MAINTAINER tchap

ADD tuneefy.conf /etc/nginx/sites-available/

RUN apt-get update && \
    apt-get install -y --fix-missing vim nano wget curl && \
    apt-get install -y nginx && \
    rm /etc/nginx/sites-enabled/default && \
    rm /etc/nginx/sites-available/default && \
    ln -sf /etc/nginx/sites-available/tuneefy.conf /etc/nginx/sites-enabled/tuneefy.conf 

# forward request and error logs to docker log collector
RUN ln -sf /dev/stdout /var/log/nginx/access.log && \
    ln -sf /dev/stderr /var/log/nginx/error.log

EXPOSE 80

CMD /usr/sbin/nginx -g "daemon off;"