FROM debian:jessie
MAINTAINER tchap

RUN apt-key adv --recv-keys --keyserver hkp://keyserver.ubuntu.com:80 0x5a16e7281be7a449 && \
    echo "deb http://dl.hhvm.com/debian jessie main" >> /etc/apt/sources.list.d/hhvm.list && \
    apt-get update && \
    apt-get install -y --fix-missing vim nano wget curl && \
    apt-get install -y software-properties-common python-software-properties && \
    apt-get install -y hhvm curl

ENV LOGNAME root

EXPOSE 9000

CMD hhvm -m server -vServer.Type=fastcgi -vServer.Port=9000 --user www-data