FORMAT: 1A
HOST: https://api.tuneefy.com

# The tuneefy API
Welcome to the **tuneefy** API. This API provides access to the **tuneefy.com** service and exposes endpoints to search and aggregate music links.


# Data Structures

## Platform

- tag: `deezer` (string)
- name: `Deezer` (string)
- mainAccentColor: `181818` (string)
- type: `streaming` (string)


## Authentication

The API endpoints require an OAuth access token. The token is necessary to authenticate requests, but as tuneefy does not have any user account, it is not used to authenticate third parties or other end users.

### OAUTH

The tuneefy API currently supports the OAuth 2 draft specification. All OAuth2 requests MUST use the SSL endpoint available at https://api.tuneefy.com/.

OAuth 2.0 is a simple and secure authentication mechanism. It allows applications to acquire an access token for tuneefy via a POST request to a token endpoint. Authentication with OAuth can be accomplished in the following steps:

  1. Register for an API key by sending a mail to ....
  2. Exchange your client id and secret for an access token
  3. Make requests passin the token in the Authorization header
  4. When your token expires, you can get a new one

### In short

+ This API uses OAuth2 for authentication,
+ A token MUST be retrieved from the authentication endpoint before issuing any request,
+ Token MUST be provided in a `Authorization` header, or via the `access_token` parameter,
+ Token MUST be provided for each request that requires authentication,




## Pagination

The API can limit the number of results returned (for `search` and `aggregate` methods).

TODO






## Response format

This API uses `Accept-Content` header to identify the locale.

`Accept-Language: en`

This header SHOULD be present in every request. If not, API MUST use the **english** language/locale.

Alternatively, all tuneefy methods support an optional return format parameter `format=json`. Note that **json** is the default response format, but **xml** and **html** are also available.

The API does *not* support **JSONP**.







## Notational Conventions

The key words "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL NOT", "SHOULD", "SHOULD NOT", "RECOMMENDED", "MAY", and "OPTIONAL" in this document are to be interpreted as described in [RFC2119](https://www.ietf.org/rfc/rfc2119).






## Representation of Date and Time

All exchange of date and time-related data MUST be done according to ISO 8601 standard and stored in UTC.

When returning date and time-related data `YYYY-MM-DDThh:mm:ss.SSSZ` format MUST be used.






## Status Codes and Errors

This API uses HTTP status codes to communicate with the API consumer.

+ `200 OK` - Response to a successful GET or POST.
+ `400 Bad Request` - Malformed request; form validation errors.
+ `401 Unauthorized` - When no or invalid authentication details are provided.
+ `404 Not Found` - When a non-existent resource is requested.
+ `405 Method Not Allowed` - Method not allowed.
+ `406 Not Acceptable` - Could not satisfy the request Accept header.





### Error response

This API returns both, machine-readable error codes and human-readable error messages in response body when an error is encountered.





## Versioning

This API uses `Api-Version` header to identify requested version. Every **minor** version SHOULD be backward compatible. However, **major** versions MAY introduce *breaking changes*.

`Api-Version: 1.0.0`

This header SHOULD be present in every request. If not, API MUST use the newest available major release.

If requested version is not available, API SHOULD try to fall back to the next available minor release.




# Group Authentication

## OAuth Access token [/token]

A valid token MUST be provided for each request that requires authentication.

### Get an access token [POST]

Allows to retrieve a valid OAuth token for your application, using the application consumer key and secret.

**Endpoint information**

|                         |     |
|-------------------------|-----|
| Requires authentication | No  |
| Has restricted scope    | No  |


+ Request
    + Attributes
        + client_id (required, string) ...  your application's tuneefy client id.
        + client_secret (required, string) ...  your application's tuneefy client secret.
        + grant_type (required, string) ... must be `client_credentials`.

+ Response 200 (application/json)

    + Headers

            X-Api-Version: 2

    + Attributes
        - token TODO






## Platforms list [/platforms{?type}]

### Retrieve all Platforms [GET]
Retrieves the list of available **Platforms**

+ Parameters
    + type (optional, string) ... The type of platform to retrieve

+ Response 200 (application/json)

    + Headers

            X-Api-Version: 2

    + Attributes
        - platforms (array[Platform])




## Platform detail [/platform/{tag}]

### Retrieve a Platform [GET]
Retrieves a specific **Platform** and its details

+ Parameters
    + tag (required, string) ... The tag of the platform to retrieve

+ Response 200 (application/json)

    + Headers

            X-Api-Version: 2

    + Attributes (Platform)

+ Response 404 (application/json)

    + Headers

            X-Api-Version: 2

    + Body

            {
                "errors": ["This platform does not exist"]
            }