---
- hosts: "{{ tuneefy_hosts }}"
  vars_files:
    - ./vars.yml
  tasks:
    - name: Set some variables
      set_fact:
        release_path: "{{ project_path }}/releases/{{ lookup('pipe','date +%Y%m%d%H%M%S') }}"
        current_path: "{{ project_path }}/current"
        shared_path: "{{ project_path }}/shared"
    - name: Retrieve current release folder
      command: readlink -f current
      register: current_release_path
      ignore_errors: true
      args:
        chdir: "{{ project_path }}"
    - name: Ensure shared folder is present
      file:
        path: "{{ shared_path }}"
        state: directory
    - name: Ensure shared logs folder is present
      file:
        path: "{{ shared_path }}/logs"
        state: directory
    - name: Create new folder
      file:
        dest={{ release_path }}
        mode=0755
        recurse=yes
        state=directory
    - name: Clone the repository
      git:
        repo: "git@github.com:tchapi/tuneefy2.git"
        dest: "{{ release_path }}"
    - name: Link .env.local file
      file:
        src={{ shared_path }}/.env.local
        dest={{ release_path }}/.env.local
        state=link
    - name: Link keys files (JWT) for the Oauth2
      file:
        src={{ shared_path }}/jwt
        dest={{ release_path }}/config/jwt
        state=link
    - name: Create the var and cache/prod folder
      file:
        dest={{ release_path }}/var/cache/prod
        mode=0775
        recurse=yes
        state=directory
        group=www-data
    - name: Link var/logs directory
      file:
        src={{ shared_path }}/logs
        dest={{ release_path }}/var/log
        state=link
    - name: Install composer dependencies
      composer:
        command: install
        working_dir: "{{ release_path }}"
        prefer_dist: yes
    - name: Remove perilous files
      file:
        path: "{{ release_path }}/{{ item }}"
        state: absent
      with_items:
        - .gitignore
        - .git
        - .php-cs-fixer.php
        - .editorconfig
        - deploy
        - LICENSE
        - README.md
        - gulpfile.js
        - examples
        - package.json
        - yarn.lock
        - codeception.yml
        - codeception.yml.dist
    - name: Creates a cron file under /etc/cron.d for updating stats and cleaning intents
      become: true
      become_user: root
      cron:
        name: "Tuneefy: Update stats"
        minute: "14"
        user: "{{ansible_user}}"
        job: "/usr/bin/php {{current_path}}/bin/console tuneefy:update-stats >> {{shared_path}}/logs/cron-job.log"
        cron_file: tuneefy_update-stats
    - name: Creates a cron file under /etc/cron.d for cleaning intents
      become: true
      become_user: root
      cron:
        name: "Tuneefy: Clean expired intents"
        minute: "18"
        user: "{{ansible_user}}"
        job: "/usr/bin/php {{current_path}}/bin/console tuneefy:clean-expired-intents >> {{shared_path}}/logs/cron-job.log"
        cron_file: tuneefy_clean-expired-intents
    - name: Creates a cron file under /etc/cron.d for cleaning expired tokens
      become: true
      become_user: root
      cron:
        name: "Tuneefy: Clear expired tokens"
        minute: "35"
        user: "{{ansible_user}}"
        job: "/usr/bin/php {{current_path}}/bin/console league:oauth2-server:clear-expired-tokens >> {{shared_path}}/logs/cron-job.log"
        cron_file: tuneefy_clean-expired-tokens
    - name: Update symlink
      file:
        src={{ release_path }}
        dest={{ current_path }}
        state=link
    - name: Restart PHP-FPM
      become: true
      become_user: root
      service:
        name: "php8.2-fpm"
        state: restarted
    - name: Give correct permissions
      file:
        state: directory
        path: "{{ current_path }}/var/cache"
        owner: debian
        group: www-data
        recurse: true
        mode: '0775'
